### ISSUE TITLE
Display synchronization errors

### ISSUE THREAD

**Issue by riccardomc** [parvaeres/parvaeres-ui#5]
We currently only report `ERROR` state for sync failures and we don't return the actual error message. See this example (UUIDs redacted):

```
curl -s https://api.poc.parvaeres.io/v1/deployment/... | jq '.Items[0].Errors'
[
  "Failed sync attempt to 68db: one or more synchronization tasks are not valid (retried 5 times)."
]

```

We could even better than the high level error condition by reporting the `syncResult` and resources in `SyncFailed` state.
```
status:
    conditions:
    - lastTransitionTime: "2020-11-24T21:32:29Z"
      message: 'Failed sync attempt to 68db: one
        or more synchronization tasks are not valid (retried 5 times).'
      type: SyncError
[...]
      phase: Failed
      retryCount: 5
      startedAt: "2020-11-24T21:27:19Z"
      syncResult:
        resources:
        - group: apps.openshift.io
          kind: DeploymentConfig
          message: the server could not find the requested resource
          name: mysql-p07
          namespace: ...
          status: SyncFailed
          syncPhase: Sync
          version: v1
```
